#!/bin/bash
echo "--Running pre-push"
EXIT_CODE=0

# --- Secrets check ---
SECRET_FILES=$(git diff --cached --name-only | grep -E 'secret(s)?\.yaml$')
for FILE in $SECRET_FILES; do
    if [ -f "$FILE" ]; then
        if ! grep -q "sops:" "$FILE"; then
            echo "--------------------------------------------------------"
            echo "ERROR: Unencrypted secret file detected: $FILE"
            echo "Please encrypt this file by running \`just encrypt $FILE\`,"
            echo "then run \`git add $FILE\`."
            echo "--------------------------------------------------------"
            EXIT_CODE=1
        fi
    fi
done

exit $EXIT_CODE
