-- Local-only: 70 more mock members (IDs ...0011 to ...0080) so that, with the 10 in
-- R__Mock_V0001, there are 80 members to develop the matching algorithm against.
-- Modeled on real Patina members: students / new grads looking for a mentor, and
-- professionals (2-20 years in) offering mentorship. Roughly 50% tech, 30% finance and
-- banking, 20% other (design, sales, business, consulting, legal, healthcare, sciences).
-- first_name is the member's role + company or school; last_name is their interests.
-- match_pref and industry_pref only use the sign-up form dropdown values.
INSERT INTO members (
    id,
    first_name,
    last_name,
    email,
    linked_in_url,
    introduction,
    referral_source,
    active,
    match_pref,
    industry_pref,
    role_pref,
    topics,
    extra_notes,
    deactivation_reason
)
VALUES
    (
        '10000000-0000-4000-8000-000000000011',
        'CS-Sophomore-Hunter',
        'Hackathons-Gaming',
        'cs-sophomore-hunter@example.com',
        'https://www.linkedin.com/in/cs-sophomore-hunter-example',
        'Priya is a sophomore at Hunter College studying Computer Science. She is looking for her first software engineering internship and spends her weekends at hackathons.',
        'Friend',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Software Engineer',
        'Hackathons, Internship search, Gaming',
        'Evenings work best.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000012',
        'Senior-SWE-Google',
        'Mentoring-Rock-Climbing',
        'senior-swe-google@example.com',
        'https://www.linkedin.com/in/senior-swe-google-example',
        'Marcus graduated from Stony Brook University and is a senior software engineer at Google, where he has worked on search infrastructure for 8 years. He loves helping students prepare for technical interviews.',
        'Patina Network newsletter',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Senior Software Engineer',
        'Mentorship, System design, Rock climbing',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000013',
        'SWE-Intern-Bloomberg',
        'Backend-Basketball',
        'swe-intern-bloomberg@example.com',
        'https://www.linkedin.com/in/swe-intern-bloomberg-example',
        'Jordan is a junior at Brooklyn College majoring in Computer Science and is interning as a software engineer at Bloomberg. She wants to strengthen her backend skills before full-time recruiting.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Software Engineer',
        'Backend development, Full-time recruiting, Basketball',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000014',
        'PM-Intern-Datadog',
        'Product-Strategy',
        'pm-intern-datadog@example.com',
        'https://www.linkedin.com/in/pm-intern-datadog-example',
        'Nadia is a current product management intern at Datadog and a senior at NYU studying Business and Computer Science. She is looking for a full-time role in product management, technical consulting, or software engineering.',
        'LinkedIn',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Product Manager',
        'Product management, Technical consulting, Career planning',
        'Virtual chats preferred.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000015',
        'New-Grad-SWE-Capital-One',
        'Cooking-Travel',
        'new-grad-swe-capital-one@example.com',
        NULL,
        'Diego is a foodie who loves to cook for friends and try every new restaurant in Queens! His goal is to visit 30 countries before he turns 30.',
        'Friend',
        TRUE,
        'Peer - I am looking for someone at a similar level',
        'Technology',
        'Software Engineer',
        'Cooking, Travel, Food',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000016',
        'Data-Scientist-Spotify',
        'ML-Music',
        'data-scientist-spotify@example.com',
        'https://www.linkedin.com/in/data-scientist-spotify-example',
        'Hana studied Statistics at Columbia and has spent 5 years as a data scientist at Spotify building recommendation models. She enjoys helping students break into data science.',
        'Patina Network event',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Data Scientist',
        'Machine learning, Recommendation systems, Music',
        'Happy to meet in Manhattan.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000017',
        'Third-Year-CS-Columbia',
        'AI-Research',
        'third-year-cs-columbia@example.com',
        'https://www.linkedin.com/in/third-year-cs-columbia-example',
        'Ethan is a third year at Columbia studying Computer Science and works as an undergraduate research assistant in an NLP lab. He is deciding between a PhD and an industry ML role.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Machine Learning Engineer',
        'AI research, Grad school, Python',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000018',
        'Engineering-Manager-Meta',
        'Leadership-Hiring',
        'engineering-manager-meta@example.com',
        'https://www.linkedin.com/in/engineering-manager-meta-example',
        'Renee went to Cornell and is an engineering manager at Meta with 12 years in the industry. She leads a team of ten engineers and is passionate about helping new grads grow.',
        'Colleague',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Engineering Manager',
        'Leadership, Hiring, Career growth',
        'Limited availability, virtual preferred.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000019',
        'CS-Grad-Student-NYU-Tandon',
        'Cybersecurity',
        'cs-grad-student-nyu-tandon@example.com',
        'https://www.linkedin.com/in/cs-grad-student-nyu-tandon-example',
        'Arjun is a first-year master''s student in Cybersecurity at NYU Tandon and works part-time at the school''s IT help desk. He hopes to land a security engineering internship next summer.',
        'LinkedIn',
        TRUE,
        'No Preference - I am open to any type of match',
        'Technology',
        'Security Engineer',
        'Cybersecurity, Graduate school, Networking',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000020',
        'Frontend-Engineer-Etsy',
        'Accessibility-Ceramics',
        'frontend-engineer-etsy@example.com',
        NULL,
        'Camille studied Computer Science at Pace University and has been a frontend engineer at Etsy for 3 years, focusing on accessibility. Outside of work she throws pottery.',
        'Instagram',
        FALSE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Frontend Engineer',
        'Accessibility, React, Ceramics',
        NULL,
        'Moved abroad and paused matching.'
    ),
    (
        '10000000-0000-4000-8000-000000000021',
        'IT-Senior-Lehman',
        'Cloud-Certifications',
        'it-senior-lehman@example.com',
        NULL,
        'Kwame is a senior at Lehman College majoring in Computer Information Systems and works as an IT support technician on campus. He is studying for his AWS certification.',
        'Community partner',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Cloud Engineer',
        'Cloud, AWS certifications, IT support',
        'Lunch breaks work well.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000022',
        'Staff-Engineer-Stripe',
        'Distributed-Systems',
        'staff-engineer-stripe@example.com',
        'https://www.linkedin.com/in/staff-engineer-stripe-example',
        'Leon graduated from Carnegie Mellon and is a staff engineer at Stripe with 15 years of experience in payments infrastructure. He enjoys mentoring early-career engineers.',
        'Colleague',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Staff Software Engineer',
        'Distributed systems, Architecture, Mentorship',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000023',
        'Recent-CS-Grad-City-College',
        'Job-Search-Anime',
        'recent-cs-grad-city-college@example.com',
        NULL,
        'Kenji just graduated and is a huge anime fan who spends his free time drawing manga-style comics. His goal is to land his first software job and save up for a trip to Tokyo!',
        'Friend',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Software Engineer',
        'Job search, Anime, Drawing',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000024',
        'Technical-Consultant-Accenture',
        'Cloud-Migration',
        'technical-consultant-accenture@example.com',
        'https://www.linkedin.com/in/technical-consultant-accenture-example',
        'Simone went to Fordham and has been a technical consultant at Accenture for 3 years, helping clients migrate to the cloud. She is thinking about a move into product management.',
        'LinkedIn',
        TRUE,
        'Peer - I am looking for someone at a similar level',
        'Technology',
        'Technical Consultant',
        'Cloud migration, Consulting, Client management',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000025',
        'Data-Analytics-Junior-Queens-College',
        'SQL-Dance',
        'data-analytics-junior-queens-college@example.com',
        'https://www.linkedin.com/in/data-analytics-junior-queens-college-example',
        'Maya is a junior at Queens College majoring in Data Science and works as a data analytics intern at a healthcare nonprofit. She also dances with her school''s K-pop dance team.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Data Analyst',
        'SQL, Data visualization, Dance',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000026',
        'Principal-Engineer-Microsoft',
        'Systems-Design',
        'principal-engineer-microsoft@example.com',
        'https://www.linkedin.com/in/principal-engineer-microsoft-example',
        'Victor studied Electrical Engineering at Georgia Tech and is a principal engineer at Microsoft with 20 years in the industry. He likes talking about career paths beyond senior engineer.',
        'Patina Network newsletter',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Principal Engineer',
        'Systems design, Technical leadership, Mentorship',
        'Weekends only.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000027',
        'CS-Freshman-Stony-Brook',
        'Web-Dev-Photography',
        'cs-freshman-stony-brook@example.com',
        NULL,
        'Lucia is a freshman at Stony Brook University majoring in Computer Science. She is building her first personal website and loves street photography.',
        'Instagram',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Software Engineer',
        'Web development, Photography, First internship',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000028',
        'Product-Manager-Squarespace',
        'AI-Products',
        'product-manager-squarespace@example.com',
        'https://www.linkedin.com/in/product-manager-squarespace-example',
        'Omar went to Baruch College and is a product manager at Squarespace with 6 years of experience, currently working on AI website tools. He moved into product from customer support.',
        'Patina Network event',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Product Manager',
        'AI products, Product discovery, Career pivots',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000029',
        'Mobile-Engineer-Uber',
        'iOS-Marathons',
        'mobile-engineer-uber@example.com',
        'https://www.linkedin.com/in/mobile-engineer-uber-example',
        'Tess is a marathon runner who has finished the NYC Marathon three times and is training for Boston. When she is not running she is trying out new coffee shops around the city.',
        'Friend',
        TRUE,
        'No Preference - I am open to any type of match',
        'Technology',
        'Mobile Engineer',
        'iOS, Running, Fitness',
        'Virtual or Queens.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000030',
        'Data-Science-Masters-Columbia',
        'NLP-Startups',
        'data-science-masters-columbia@example.com',
        'https://www.linkedin.com/in/data-science-masters-columbia-example',
        'Wei is a master''s student in Data Science at Columbia and is interning at an AI startup in Flatiron. He wants to work on language models after graduating.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Data Scientist',
        'NLP, Startups, Machine learning',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000031',
        'DevOps-Engineer-MongoDB',
        'Kubernetes-Hiking',
        'devops-engineer-mongodb@example.com',
        'https://www.linkedin.com/in/devops-engineer-mongodb-example',
        'Isaac studied Computer Science at Rutgers and has been a DevOps engineer at MongoDB for 4 years. On weekends he is usually hiking upstate.',
        'LinkedIn',
        TRUE,
        'Peer - I am looking for someone at a similar level',
        'Technology',
        'DevOps Engineer',
        'Kubernetes, Observability, Hiking',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000032',
        'SWE-Intern-JPMorgan',
        'Fintech-Chess',
        'swe-intern-jpmorgan@example.com',
        'https://www.linkedin.com/in/swe-intern-jpmorgan-example',
        'Farah is a sophomore at Baruch College majoring in Computer Information Systems and is a software engineering intern at JPMorgan Chase. She is curious about how technology works in banking.',
        'Community partner',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Software Engineer',
        'Fintech, Java, Chess',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000033',
        'Security-Engineer-CrowdStrike',
        'AppSec-CTFs',
        'security-engineer-crowdstrike@example.com',
        'https://www.linkedin.com/in/security-engineer-crowdstrike-example',
        'Rafael went to John Jay College and has been a security engineer at CrowdStrike for 7 years. He organizes CTF competitions for local students.',
        'Friend',
        FALSE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Security Engineer',
        'Application security, CTFs, Cloud security',
        'Virtual only.',
        'Started a new job and is taking a break.'
    ),
    (
        '10000000-0000-4000-8000-000000000034',
        'CS-Senior-Rutgers',
        'Game-Dev',
        'cs-senior-rutgers@example.com',
        NULL,
        'Tyler is a senior at Rutgers studying Computer Science and has been interning at a small indie game studio for close to a year. He is looking for full-time roles in game development.',
        'LinkedIn',
        TRUE,
        'Peer - I am looking for someone at a similar level',
        'Technology',
        'Game Developer',
        'Game development, Unity, Full-time recruiting',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000035',
        'Solutions-Engineer-Salesforce',
        'Customer-Facing-Tech',
        'solutions-engineer-salesforce@example.com',
        'https://www.linkedin.com/in/solutions-engineer-salesforce-example',
        'Grace studied Information Systems at Binghamton and has been a solutions engineer at Salesforce for 2 years. She is looking for advice on moving into a senior role.',
        'Colleague',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Solutions Engineer',
        'Solutions engineering, Sales engineering, Career growth',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000036',
        'Data-Engineer-NYTimes',
        'Data-Pipelines-Baking',
        'data-engineer-nytimes@example.com',
        'https://www.linkedin.com/in/data-engineer-nytimes-example',
        'Nora is a passionate home baker who brings sourdough to every team meeting. Her goal is to open a small bakery one day while still building data tools on the side.',
        'Patina Network newsletter',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Data Engineer',
        'Baking, Data pipelines, Community',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000037',
        'Computer-Eng-Sophomore-Cooper-Union',
        'Robotics-Hardware',
        'computer-eng-sophomore-cooper-union@example.com',
        NULL,
        'Malik is a sophomore at Cooper Union studying Electrical and Computer Engineering. He builds robots with his school''s robotics club and wants to work in hardware.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Hardware Engineer',
        'Robotics, Embedded systems, Hardware',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000038',
        'ML-Engineer-IBM',
        'GenAI-Volunteering',
        'ml-engineer-ibm@example.com',
        'https://www.linkedin.com/in/ml-engineer-ibm-example',
        'Anjali went to NYU and is a machine learning engineer at IBM with 10 years of experience. She volunteers teaching coding to high schoolers in the Bronx.',
        'Patina Network event',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Machine Learning Engineer',
        'Generative AI, Volunteering, Mentorship',
        'Available Friday mornings.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000039',
        'Cybersecurity-Junior-John-Jay',
        'Ethical-Hacking',
        'cybersecurity-junior-john-jay@example.com',
        'https://www.linkedin.com/in/cybersecurity-junior-john-jay-example',
        'Luis is a junior at John Jay College majoring in Computer Science and Information Security and works part-time at a managed IT services company. He is studying for Security+.',
        'Community partner',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Security Analyst',
        'Ethical hacking, Security certifications, CTFs',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000040',
        'Backend-Engineer-Plaid',
        'APIs-Cycling',
        'backend-engineer-plaid@example.com',
        'https://www.linkedin.com/in/backend-engineer-plaid-example',
        'Sam studied Computer Science at Hunter College and has been a backend engineer at Plaid for 3 years. They bike to work every day, rain or shine.',
        'LinkedIn',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Backend Engineer',
        'APIs, Fintech, Cycling',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000041',
        'New-Grad-SWE-Amazon',
        'Cloud-Volleyball',
        'new-grad-swe-amazon@example.com',
        'https://www.linkedin.com/in/new-grad-swe-amazon-example',
        'Bianca just graduated from Brooklyn College with a degree in Computer Science and started as a software engineer at Amazon Web Services. She plays in a weekend volleyball league.',
        'University alumni group',
        TRUE,
        'Peer - I am looking for someone at a similar level',
        'Technology',
        'Software Engineer',
        'Cloud, New grad life, Volleyball',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000042',
        'TPM-Intern-Microsoft',
        'Program-Management',
        'tpm-intern-microsoft@example.com',
        'https://www.linkedin.com/in/tpm-intern-microsoft-example',
        'Daniel is a senior at Cornell studying Information Science and is a technical program management intern at Microsoft. He wants to figure out the difference between TPM and PM roles.',
        'Patina Network newsletter',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Technical Program Manager',
        'Program management, Product management, Communication',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000043',
        'Senior-Data-Analyst-Peloton',
        'Analytics-Fitness',
        'senior-data-analyst-peloton@example.com',
        'https://www.linkedin.com/in/senior-data-analyst-peloton-example',
        'Jasmine is a fitness lover who never misses her morning spin class! Her goal is to run a half marathon this year and get her friends to join her.',
        'Instagram',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Technology',
        'Data Analyst',
        'Fitness, Spin classes, Wellness',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000044',
        'Full-Stack-Engineer-Shopify',
        'Side-Projects-Board-Games',
        'full-stack-engineer-shopify@example.com',
        NULL,
        'Owen studied Computer Science at Queens College and has been a full stack engineer at Shopify for 2 years. He hosts a board game night every Friday.',
        'Friend',
        FALSE,
        'Peer - I am looking for someone at a similar level',
        'Technology',
        'Full Stack Engineer',
        'Side projects, Board games, TypeScript',
        NULL,
        'Asked to be removed from future rounds.'
    ),
    (
        '10000000-0000-4000-8000-000000000045',
        'Bootcamp-Grad-Pursuit',
        'Career-Switch-Music',
        'bootcamp-grad-pursuit@example.com',
        NULL,
        'Andre is very passionate about learning technical subjects and finding ways to overcome obstacles. He switched careers from music production and is curious and ambitious about his first tech role.',
        'Community partner',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Technology',
        'Software Engineer',
        'Career switch, Music production, JavaScript',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000046',
        'Finance-Junior-Baruch',
        'Investment-Banking',
        'finance-junior-baruch@example.com',
        'https://www.linkedin.com/in/finance-junior-baruch-example',
        'Kayla is a junior at Baruch College majoring in Finance and is recruiting for investment banking summer analyst roles. She is the VP of her school''s finance club.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Finance',
        'Investment Banking Analyst',
        'Investment banking, Recruiting, Networking',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000047',
        'IB-Analyst-Morgan-Stanley',
        'M&A-Pickleball',
        'ib-analyst-morgan-stanley@example.com',
        'https://www.linkedin.com/in/ib-analyst-morgan-stanley-example',
        'Brandon went to Fordham and has been an investment banking analyst at Morgan Stanley for 2 years, working on tech M&A deals. He plays pickleball whenever he finds the time.',
        'Colleague',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Finance',
        'Investment Banking Analyst',
        'M&A, Work-life balance, Pickleball',
        'Weekends preferred.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000048',
        'Accounting-Senior-Baruch',
        'CPA-Audit',
        'accounting-senior-baruch@example.com',
        'https://www.linkedin.com/in/accounting-senior-baruch-example',
        'Mei is a senior at Baruch College majoring in Accounting and is an audit intern at Deloitte. She is starting to study for the CPA exam.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Finance',
        'Auditor',
        'CPA exam, Audit, Big Four',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000049',
        'Portfolio-Manager-BlackRock',
        'Fixed-Income-Mentoring',
        'portfolio-manager-blackrock@example.com',
        'https://www.linkedin.com/in/portfolio-manager-blackrock-example',
        'Catherine graduated from Wharton and is a portfolio manager at BlackRock with 15 years in fixed income. She mentors women early in their finance careers.',
        'Patina Network event',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Finance',
        'Portfolio Manager',
        'Fixed income, Investing, Women in finance',
        'Available Friday mornings.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000050',
        'Econ-Sophomore-Hunter',
        'Quant-Trading',
        'econ-sophomore-hunter@example.com',
        NULL,
        'Ivan is a sophomore at Hunter College double majoring in Economics and Mathematics. He is teaching himself Python to prepare for quant trading internships.',
        'Friend',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Finance',
        'Quantitative Trader',
        'Quant trading, Math, Python',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000051',
        'Risk-Analyst-Citi',
        'Credit-Risk-Yoga',
        'risk-analyst-citi@example.com',
        'https://www.linkedin.com/in/risk-analyst-citi-example',
        'Sofia is a yoga teacher on the weekends and loves exploring new neighborhoods in the city. Her goal is to do a month-long yoga retreat in Bali.',
        'Instagram',
        TRUE,
        'Peer - I am looking for someone at a similar level',
        'Finance',
        'Risk Analyst',
        'Yoga, Meditation, Travel',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000052',
        'New-Grad-Financial-Analyst-AmEx',
        'FP&A-Excel',
        'new-grad-financial-analyst-amex@example.com',
        'https://www.linkedin.com/in/new-grad-financial-analyst-amex-example',
        'Jamal just graduated from St. John''s University with a degree in Finance and started as a financial analyst in American Express''s FP&A rotational program.',
        'LinkedIn',
        TRUE,
        'No Preference - I am open to any type of match',
        'Finance',
        'Financial Analyst',
        'FP&A, Excel modeling, Corporate finance',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000053',
        'Wealth-Advisor-Merrill',
        'Personal-Finance',
        'wealth-advisor-merrill@example.com',
        'https://www.linkedin.com/in/wealth-advisor-merrill-example',
        'Patricia went to Pace University and has been a wealth advisor at Merrill for 9 years. She is passionate about financial literacy for first-generation students.',
        'Patina Network newsletter',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Finance',
        'Financial Advisor',
        'Personal finance, Wealth management, Client relationships',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000054',
        'Commercial-Banking-Analyst-Wells-Fargo',
        'Lending-Basketball',
        'commercial-banking-analyst-wells-fargo@example.com',
        NULL,
        'Chris graduated from Baruch College last year and is a commercial banking analyst at Wells Fargo. He plays pickup basketball at the Chelsea Piers courts.',
        'Colleague',
        TRUE,
        'Peer - I am looking for someone at a similar level',
        'Finance',
        'Commercial Banking Analyst',
        'Commercial lending, Credit analysis, Basketball',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000055',
        'Finance-Freshman-NYU-Stern',
        'Venture-Capital',
        'finance-freshman-nyu-stern@example.com',
        NULL,
        'Ava is a freshman at NYU Stern studying Finance. She is curious about venture capital and joined her school''s startup investing club.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Finance',
        'Venture Capital Analyst',
        'Venture capital, Startups, Networking',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000056',
        'VP-Equity-Research-Goldman-Sachs',
        'Tech-Stocks',
        'vp-equity-research-goldman-sachs@example.com',
        'https://www.linkedin.com/in/vp-equity-research-goldman-sachs-example',
        'Henry went to Columbia and is a vice president in equity research at Goldman Sachs with 11 years covering technology stocks. He likes helping students prep for finance interviews.',
        'Patina Network event',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Finance',
        'Equity Research Analyst',
        'Equity research, Tech stocks, Career growth',
        'Limited availability, virtual preferred.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000057',
        'Quant-Researcher-Two-Sigma',
        'Statistics-Poker',
        'quant-researcher-two-sigma@example.com',
        'https://www.linkedin.com/in/quant-researcher-two-sigma-example',
        'Lin studied Mathematics at MIT and has been a quantitative researcher at Two Sigma for 6 years. She is a regular at a friendly weekly poker game.',
        'Colleague',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Finance',
        'Quantitative Researcher',
        'Statistics, Quant research, Poker',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000058',
        'Math-Senior-Brooklyn-College',
        'Actuarial-Exams',
        'math-senior-brooklyn-college@example.com',
        'https://www.linkedin.com/in/math-senior-brooklyn-college-example',
        'Yusuf is a senior at Brooklyn College majoring in Mathematics and is an actuarial intern at MetLife. He has passed his first two actuarial exams.',
        'Community partner',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Finance',
        'Actuary',
        'Actuarial exams, Insurance, Statistics',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000059',
        'PE-Associate-KKR',
        'Deal-Sourcing',
        'pe-associate-kkr@example.com',
        'https://www.linkedin.com/in/pe-associate-kkr-example',
        'Natalie went to Georgetown and is a private equity associate at KKR with 4 years of experience, after two years in investment banking.',
        'LinkedIn',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Finance',
        'Private Equity Associate',
        'Private equity, Deal sourcing, Investment banking exits',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000060',
        'Accounting-Junior-Queens-College',
        'Tax-Volunteering',
        'accounting-junior-queens-college@example.com',
        NULL,
        'Elena is a junior at Queens College majoring in Accounting and volunteers preparing free tax returns for her community. She works part-time at a local accounting firm.',
        'Community partner',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Finance',
        'Tax Accountant',
        'Tax, Volunteering, Accounting',
        'Evenings preferred.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000061',
        'Treasury-Analyst-Pfizer',
        'Corporate-Finance-Travel',
        'treasury-analyst-pfizer@example.com',
        'https://www.linkedin.com/in/treasury-analyst-pfizer-example',
        'Mateo is a travel junkie who has been to 25 countries and is learning his fourth language! He loves eating his way through every new city he visits.',
        'Friend',
        TRUE,
        'Peer - I am looking for someone at a similar level',
        'Finance',
        'Treasury Analyst',
        'Travel, Food, Languages',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000062',
        'Fintech-Ops-Analyst-Robinhood',
        'Crypto',
        'fintech-ops-analyst-robinhood@example.com',
        NULL,
        'Zoe studied Economics at SUNY Albany and has been an operations analyst at Robinhood for 3 years. She is interested in crypto and digital assets.',
        'Instagram',
        FALSE,
        'Peer - I am looking for someone at a similar level',
        'Finance',
        'Operations Analyst',
        'Crypto, Fintech, Operations',
        NULL,
        'Moved out of state and paused matching.'
    ),
    (
        '10000000-0000-4000-8000-000000000063',
        'Econ-Grad-Student-Columbia-SIPA',
        'Public-Finance',
        'econ-grad-student-columbia-sipa@example.com',
        'https://www.linkedin.com/in/econ-grad-student-columbia-sipa-example',
        'Amir is a second-year master''s student at Columbia SIPA focusing on economic policy and is interning in the city''s Office of Management and Budget.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Finance',
        'Public Finance Analyst',
        'Public finance, Policy, Municipal bonds',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000064',
        'Credit-Analyst-Moodys',
        'Ratings-Cooking',
        'credit-analyst-moodys@example.com',
        'https://www.linkedin.com/in/credit-analyst-moodys-example',
        'Rachel is a cool person who loves to host dinner parties and grow her own herbs on her fire escape. Her goal is to write a cookbook of her grandmother''s recipes.',
        'Patina Network newsletter',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Finance',
        'Credit Analyst',
        'Cooking, Dinner parties, Gardening',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000065',
        'Business-Sophomore-Baruch',
        'Banking-Personal-Growth',
        'business-sophomore-baruch@example.com',
        NULL,
        'Kevin is a sophomore at Baruch College studying Business Administration and works as a bank teller at Chase. He wants to move into a corporate banking role.',
        'Friend',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Finance',
        'Banker',
        'Banking, Personal growth, Public speaking',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000066',
        'Controller-Betterment',
        'Accounting-Leadership',
        'controller-betterment@example.com',
        'https://www.linkedin.com/in/controller-betterment-example',
        'Linda graduated from NYU and is the controller at Betterment with 14 years in accounting. She started her career at a Big Four firm.',
        'Colleague',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Finance',
        'Controller',
        'Accounting leadership, Fintech, CPA',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000067',
        'Account-Executive-Oracle',
        'B2B-Sales',
        'account-executive-oracle@example.com',
        'https://www.linkedin.com/in/account-executive-oracle-example',
        'Derek went to Hofstra and has been an account executive at Oracle for 4 years selling cloud software to enterprises. He loves helping people break into tech sales.',
        'LinkedIn',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Business',
        'Account Executive',
        'B2B sales, Negotiation, Tech sales',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000068',
        'Nursing-Junior-Hunter',
        'Healthcare-Tech',
        'nursing-junior-hunter@example.com',
        NULL,
        'Aisha is a junior at Hunter College''s nursing school and works as a patient care tech at Mount Sinai. She is curious about how technology can improve patient care.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Other',
        'Nurse',
        'Healthcare, Health tech, Nursing',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000069',
        'Product-Designer-Duolingo',
        'Design-Systems',
        'product-designer-duolingo@example.com',
        'https://www.linkedin.com/in/product-designer-duolingo-example',
        'Julia studied Graphic Design at Pratt and has been a product designer at Duolingo for 5 years. She enjoys giving portfolio feedback to students.',
        'Patina Network event',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Design',
        'Product Designer',
        'Design systems, Portfolio reviews, Figma',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000070',
        'Biology-PhD-Weill-Cornell',
        'Biotech-Travel',
        'biology-phd-weill-cornell@example.com',
        'https://www.linkedin.com/in/biology-phd-weill-cornell-example',
        'Benjamin loves to travel and has hiked in national parks across the country! His goal is to explain science to everyone in a way that is fun.',
        'Friend',
        TRUE,
        'No Preference - I am open to any type of match',
        'Other',
        'Research Scientist',
        'Travel, Hiking, Science communication',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000071',
        'UX-Design-Senior-Parsons',
        'Portfolio-Figma',
        'ux-design-senior-parsons@example.com',
        'https://www.linkedin.com/in/ux-design-senior-parsons-example',
        'Chloe is a senior at Parsons studying Communication Design and is a UX design intern at a fintech startup. She is putting together her portfolio for full-time roles.',
        'Instagram',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Design',
        'UX Designer',
        'UX design, Portfolio, User research',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000072',
        'Management-Consultant-Deloitte',
        'Public-Sector-Running',
        'management-consultant-deloitte@example.com',
        'https://www.linkedin.com/in/management-consultant-deloitte-example',
        'Danielle went to Syracuse and has 10 years of experience as a management consultant at Deloitte modernizing government technology. Outside of work, she is training for a triathlon.',
        'Colleague',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Business',
        'Management Consultant',
        'Public sector, Process improvement, Running',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000073',
        'Paralegal-Skadden',
        'Law-School-LSAT',
        'paralegal-skadden@example.com',
        'https://www.linkedin.com/in/paralegal-skadden-example',
        'Gabriel graduated from Fordham with a degree in Political Science and has been a paralegal at Skadden for 2 years. He is studying for the LSAT and applying to law school.',
        'LinkedIn',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Other',
        'Lawyer',
        'Law school, LSAT, Corporate law',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000074',
        'Marketing-Junior-Fordham',
        'Content-Creation',
        'marketing-junior-fordham@example.com',
        NULL,
        'Olivia is a junior at Fordham majoring in Marketing and is a social media intern at a beauty brand. She runs a small TikTok account about thrifting.',
        'Instagram',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Business',
        'Marketing Manager',
        'Content creation, Social media, Brand marketing',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000075',
        'Corporate-Attorney-Cravath',
        'Tech-Law',
        'corporate-attorney-cravath@example.com',
        'https://www.linkedin.com/in/corporate-attorney-cravath-example',
        'Michelle graduated from Columbia Law School and is a corporate attorney at Cravath with 8 years of experience advising tech companies. She likes talking with students considering law school.',
        'Patina Network newsletter',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Other',
        'Corporate Attorney',
        'Tech law, Law school, Career paths',
        'Weekends only.',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000076',
        'New-Grad-Business-Analyst-McKinsey',
        'Consulting-Case-Prep',
        'new-grad-business-analyst-mckinsey@example.com',
        'https://www.linkedin.com/in/new-grad-business-analyst-mckinsey-example',
        'Ravi just graduated from NYU Stern and started as a business analyst at McKinsey. He is happy to help with case interview prep.',
        'University alumni group',
        TRUE,
        'Peer - I am looking for someone at a similar level',
        'Business',
        'Business Analyst',
        'Consulting, Case interviews, Strategy',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000077',
        'SDR-HubSpot',
        'Tech-Sales-Hip-Hop',
        'sdr-hubspot@example.com',
        NULL,
        'Tre went to Lehman College and has been a sales development rep at HubSpot for 2 years. He produces hip hop beats in his spare time.',
        'Friend',
        FALSE,
        'Peer - I am looking for someone at a similar level',
        'Business',
        'Sales Development Representative',
        'Tech sales, Cold calling, Hip hop',
        NULL,
        'Asked to pause matching for the semester.'
    ),
    (
        '10000000-0000-4000-8000-000000000078',
        'Pre-Med-Junior-NYU',
        'Public-Health',
        'pre-med-junior-nyu@example.com',
        'https://www.linkedin.com/in/pre-med-junior-nyu-example',
        'Fatima is a junior at NYU majoring in Biology on the pre-med track and volunteers at a community health clinic. She is preparing for the MCAT.',
        'Community partner',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Other',
        'Physician',
        'Medicine, Public health, MCAT',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000079',
        'Freelance-UI-Designer',
        'Illustration-Thrifting',
        'freelance-ui-designer@example.com',
        NULL,
        'Noah is an artist at heart who loves illustrating and hunting for vintage finds at thrift stores! His goal is to have his own art show in Brooklyn.',
        'Instagram',
        TRUE,
        'No Preference - I am open to any type of match',
        'Design',
        'UI Designer',
        'Illustration, Thrifting, Art',
        NULL,
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000080',
        'HR-Business-Partner-LOreal',
        'People-Ops',
        'hr-business-partner-loreal@example.com',
        'https://www.linkedin.com/in/hr-business-partner-loreal-example',
        'Stephanie went to Rutgers and is an HR business partner at L''Oreal with 7 years in people operations. She loves helping students polish their resumes.',
        'Patina Network event',
        TRUE,
        'Mentee - I am looking to provide guidance to someone with less experience',
        'Business',
        'HR Business Partner',
        'People operations, Recruiting, Career coaching',
        NULL,
        NULL
    )
ON CONFLICT (id) DO UPDATE SET
    first_name = EXCLUDED.first_name,
    last_name = EXCLUDED.last_name,
    email = EXCLUDED.email,
    linked_in_url = EXCLUDED.linked_in_url,
    introduction = EXCLUDED.introduction,
    referral_source = EXCLUDED.referral_source,
    active = EXCLUDED.active,
    match_pref = EXCLUDED.match_pref,
    industry_pref = EXCLUDED.industry_pref,
    role_pref = EXCLUDED.role_pref,
    topics = EXCLUDED.topics,
    extra_notes = EXCLUDED.extra_notes,
    deactivation_reason = EXCLUDED.deactivation_reason;
