INSERT INTO members (
    id,
    first_name,
    last_name,
    email,
    linked_in_url,
    introduction,
    referral_source,
    active,
    match_pref,
    industry_pref,
    role_pref,
    topics,
    extra_notes
)
VALUES
    (
        '10000000-0000-4000-8000-000000000001',
        'Avery',
        'Chen',
        'avery.chen@example.com',
        'https://www.linkedin.com/in/avery-chen-example',
        'Product designer interested in making financial tools easier to use.',
        'Patina Network newsletter',
        TRUE,
        'Peer - I want to meet someone with similar experience',
        'Financial Technology',
        'Product Designer',
        'Design systems, Financial literacy, Career growth',
        'Available for coffee in Manhattan or a virtual chat.'
    ),
    (
        '10000000-0000-4000-8000-000000000002',
        'Jordan',
        'Williams',
        'jordan.williams@example.com',
        'https://www.linkedin.com/in/jordan-williams-example',
        'Backend engineer building reliable systems for healthcare teams.',
        'Friend',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Healthcare Technology',
        'Software Engineer',
        'Distributed systems, Leadership, Open source',
        'Usually available after work on Tuesdays and Thursdays.'
    ),
    (
        '10000000-0000-4000-8000-000000000003',
        'Priya',
        'Patel',
        'priya.patel@example.com',
        'https://www.linkedin.com/in/priya-patel-example',
        'Founder working on software that helps small businesses measure emissions.',
        'Patina Network event',
        TRUE,
        'Peer - I want to exchange ideas with another builder',
        'Climate Technology',
        'Founder',
        'Fundraising, Sustainability, Product strategy',
        'Happy to meet virtually or in Brooklyn.'
    ),
    (
        '10000000-0000-4000-8000-000000000004',
        'Marcus',
        'Johnson',
        'marcus.johnson@example.com',
        NULL,
        'Data analyst focused on improving outcomes for public school students.',
        'Colleague',
        FALSE,
        'Mentor - I can offer guidance to someone earlier in their career',
        'Education',
        'Data Analyst',
        'Analytics, Public policy, Mentorship',
        'Taking a break from matching this month.'
    ),
    (
        '10000000-0000-4000-8000-000000000005',
        'Sofia',
        'Rodriguez',
        'sofia.rodriguez@example.com',
        'https://www.linkedin.com/in/sofia-rodriguez-example',
        'Community program director connecting volunteers with neighborhood nonprofits.',
        'Community partner',
        TRUE,
        'Open - I am happy to meet a peer, mentor, or mentee',
        'Nonprofit',
        'Program Director',
        'Community building, Social impact, Volunteer engagement',
        'Prefers an in-person conversation when possible.'
    ),
    (
        '10000000-0000-4000-8000-000000000006',
        'Ethan',
        'Kim',
        'ethan.kim@example.com',
        'https://www.linkedin.com/in/ethan-kim-example',
        'Graduate student researching responsible machine learning applications.',
        'University alumni group',
        TRUE,
        'Mentor - I am looking for guidance from someone with more experience',
        'Artificial Intelligence',
        'Graduate Researcher',
        'Responsible AI, Research careers, Entrepreneurship',
        NULL
    ),
    (
        '10000000-0000-4000-8000-000000000007',
        'Nia',
        'Thompson',
        'nia.thompson@example.com',
        NULL,
        'Marketing strategist helping independent creators grow sustainable audiences.',
        'LinkedIn',
        TRUE,
        'Peer - I want to meet someone with similar experience',
        'Media',
        'Marketing Strategist',
        'Brand strategy, Creator economy, Storytelling',
        'Virtual chats work best during weekday mornings.'
    ),
    (
        '10000000-0000-4000-8000-000000000008',
        'Leo',
        'Martinez',
        'leo.martinez@example.com',
        'https://www.linkedin.com/in/leo-martinez-example',
        'Operations manager interested in technology-enabled hospitality experiences.',
        'Friend',
        TRUE,
        'Open - I am happy to meet a peer, mentor, or mentee',
        'Hospitality',
        'Operations Manager',
        'Operations, Customer experience, Small business',
        'Available in Queens or by video call.'
    ),
    (
        '10000000-0000-4000-8000-000000000009',
        'Maya',
        'Brooks',
        'maya.brooks@example.com',
        'https://www.linkedin.com/in/maya-brooks-example',
        'People operations leader building inclusive teams at growing companies.',
        'Patina Network event',
        TRUE,
        'Mentor - I can offer guidance to someone earlier in their career',
        'Professional Services',
        'People Operations Director',
        'Inclusive hiring, Management, Organizational design',
        'Open to meeting anywhere near a major subway line.'
    ),
    (
        '10000000-0000-4000-8000-000000000010',
        'Noah',
        'Okafor',
        'noah.okafor@example.com',
        NULL,
        'Independent consultant helping local retailers modernize their operations.',
        'Community partner',
        FALSE,
        'Peer - I want to exchange ideas with another builder',
        'Retail',
        'Business Consultant',
        'Digital transformation, Consulting, Local business',
        'Inactive seed record for testing member status filters.'
    )
ON CONFLICT (email) DO NOTHING;
