/**
 * Types generated by `openapi-typescript` from the backend OpenAPI spec.
 *
 * This is a placeholder until codegen is wired up. Regenerate with, e.g.:
 *   pnpm openapi-typescript http://localhost:8080/v3/api-docs -o src/lib/api/schema.d.ts
 *
 * Once populated, `lib/api/client.ts` and domain `api/` hooks can be typed
 * against `paths` / `components` from this file.
 */

export type paths = Record<string, never>;
export type components = Record<string, never>;
