name: Deploy to staging
run-name: Deploying to staging triggered by ${{ github.actor }}

concurrency:
  group: deploy-staging
  cancel-in-progress: true

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  backendPretest:
    name: Backend Pretests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run workflow
        uses: ./.github/composite/test/backend-pretest

  frontendPretest:
    name: Frontend Pretests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: js
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run workflow
        uses: ./.github/composite/test/frontend-pretest

  backendTest:
    name: Backend Tests
    runs-on: ubuntu-latest
    needs: backendPretest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run workflow
        uses: ./.github/composite/test/backend-test

  frontendTest:
    name: Frontend Tests
    runs-on: ubuntu-latest
    needs: frontendPretest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run workflow
        uses: ./.github/composite/test/frontend-test

  migrateDatabase:
    name: Migrate Staging Database
    runs-on: ubuntu-latest
    needs: [backendTest, frontendTest]


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0


      - name: Setup CI
        uses: ./.github/composite/setup-ci
        with:
          SECRETS: ${{ toJSON(secrets) }}

      - name: Run workflow
        uses: ./.github/composite/db/migrate
        with:
          ENVIRONMENT: staging
  
  buildImage:
    name: Build Docker Image & Upload to Registry
    runs-on: ubuntu-latest
    needs: [migrateDatabase]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup CI
        uses: ./.github/composite/setup-ci
        with:
          SECRETS: ${{ toJSON(secrets) }}

      - name: Run workflow
        uses: ./.github/composite/build-image
        with:
          ENVIRONMENT: staging
          DOCKER_UPLOAD: true

  updateK8sTag:
    name: Change Tag in K8s 
    runs-on: ubuntu-latest
    needs: [buildImage]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CI
        uses: ./.github/composite/setup-ci
        with:
          SECRETS: ${{ toJSON(secrets) }}

      - name: Run Workflow
        uses: ./.github/composite/update-tag
        with:
          ENVIRONMENT: staging
          VERSION: ${{ github.ref_name }}